CREATE TABLE [dwh].[asto_DataValues_CT] (
    [DvId]              INT              IDENTITY (1, 1) NOT NULL,
    [ProdDate]          DATE             NOT NULL,
    [__$start_lsn]      BINARY (10)      NOT NULL,
    [__$end_lsn]        BINARY (10)      NULL,
    [__$seqval]         BINARY (10)      NOT NULL,
    [__$operation]      INT              NOT NULL,
    [__$update_mask]    VARBINARY (128)  NULL,
    [Id]                BIGINT           NULL,
    [ClosePeriodId]     INT              NULL,
    [PeriodTypeId]      SMALLINT         NOT NULL,
    [ReportId]          INT              NOT NULL,
    [ItemId]            INT              DEFAULT ((0)) NOT NULL,
    [RowId]             BIGINT           NULL,
    [ElementId]         SMALLINT         NULL,
    [DataTypeId]        TINYINT          NULL,
    [UnitId]            SMALLINT         NULL,
    [Value]             DECIMAL (19, 10) NULL,
    [CauseChanged]      NVARCHAR (256)   NULL,
    [DateCreate]        DATETIME2 (3)    NULL,
    [DateUpdate]        DATETIME2 (3)    NULL,
    [ShipConsignmentId] INT              NULL,
    [DataSourceCellId]  TINYINT          NULL,
    [HistoryUserId]     SMALLINT         NULL,
    [__$command_id]     INT              NULL,
    [IsValueChanged]    BIT              DEFAULT ((1)) NOT NULL,
    [ErrorStatus]       TINYINT          DEFAULT ((0)) NOT NULL,
    [ErrorNumber]       SMALLINT         DEFAULT ((0)) NOT NULL,
    [ProcessedTime]     DATETIME2 (3)    NULL,
    [TranceDate]        DATETIME2 (3)    DEFAULT (sysdatetime()) NULL,
    [CycleNumber]       INT              DEFAULT ((1)) NOT NULL,
    [LsnTime]           DATETIME         NOT NULL,
    CONSTRAINT [PK_dwh_asto_DataValues_CT] PRIMARY KEY CLUSTERED ([ProdDate] ASC, [DvId] ASC) ON [CDCPartitionSchema] ([ProdDate])
) ON [CDCPartitionSchema] ([ProdDate]);

